#!/usr/bin/env python
"""Generate blur-up placeholders (base64) for Next.js Image component."""

import base64
from pathlib import Path
from PIL import Image
import io

IMAGES_DIR = Path("public/images")
OUTPUT_FILE = Path("src/lib/placeholders.ts")

# Images that are actually used in the codebase
USED_IMAGES = [
    "eco.jpg",  # Hero image
    "o.jpg",  # Feature 1: 100% Organic
    "handmade.jpg",  # Feature 2: Eco-Handmade
    "wrapping.jpg",  # Feature 3: Zero Waste
]


def generate_placeholder(image_path: Path, max_size: int = 20) -> str:
    """Generate a tiny base64 placeholder for blur-up effect."""
    with Image.open(image_path) as img:
        # Convert to RGB if needed
        if img.mode in ("RGBA", "LA", "P"):
            img = img.convert("RGB")
        # Resize to tiny
        img.thumbnail((max_size, max_size))
        # Save to bytes
        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=30)
        buffer.seek(0)
        # Encode to base64
        b64 = base64.b64encode(buffer.read()).decode("utf-8")
        return f"data:image/jpeg;base64,{b64}"


def main():
    placeholders = {}

    for img_name in USED_IMAGES:
        img_path = IMAGES_DIR / img_name
        if img_path.exists():
            placeholder = generate_placeholder(img_path)
            # Use filename without extension as key
            key = img_path.stem
            placeholders[key] = placeholder
            print(f"Generated placeholder for {img_name} ({len(placeholder)} chars)")
        else:
            print(f"WARNING: {img_name} not found")

    # Write TypeScript file
    ts_content = "// Auto-generated blur-up placeholders\n"
    ts_content += "// Generated by scripts/generate_placeholders.py\n\n"
    ts_content += "export const placeholders: Record<string, string> = {\n"
    for key, value in placeholders.items():
        ts_content += f'  {key}: "{value}",\n'
    ts_content += "};\n"

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(ts_content)
    print(f"\nWrote {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
